### ISSUE TITLE
Duplication of rows when using _ANY_EVENT as a predicate for windows.

### ISSUE THREAD

**Issue by Oufattole** [justin13601/ACES#73] opened 2024-07-21 22:35 UTC
Aces generates duplicate rows when I define windows around the _ANY_EVENT (random events) predicate. I would expect each row to be unique. Here is some minimial code in colab to reproduce the issue:
https://colab.research.google.com/drive/1qER-KA3o6jU3i8StdsNFZrLrdaQ6FA7l?usp=sharing

The TLDR is that on this simple dataframe of three rows:
![image](https://github.com/user-attachments/assets/a81e9fa7-8b76-48eb-bed0-885b53a6e89c)

I get this output dataframe from aces:
![image](https://github.com/user-attachments/assets/2360a3a8-1d23-4ee6-8f59-3f7cbe639ec6)

And this output dataframe has only 3 unique rows:
![image](https://github.com/user-attachments/assets/9e9923e3-0e3c-4712-8993-7578beb935f1)

I've seen the issue on a slightly larger test dataset of 62 rows where Aces outputs around 152 rows but there are only 62 unique rows.

**Comment by mmcdermott** [comment] 2024-08-22 16:58
This has been reported to be occurring on a more real-world case with a readmission predictor config. However, I'm not able to reproduce this issue locally. So, for now, the primary task of this config (which is on @Oufattole) is to provide a test case that we can reproduce on up to date code, so we can begin to iterate on it.

**Comment by justin13601** [comment] 2024-08-22 20:24
@mmcdermott were you able to reproduce the issue with @Oufattole's original example locally? I seem to still be able to on my end with the most updated version (main branch code). The result returns 5 rows when it should be the 3 per the screenshots

**Comment by mmcdermott** [comment] 2024-08-22 21:13
See the PR I pushed @justin13601 which adds a test based on his example that passes. Though maybe I did something wrong in my setup?

**Comment by mmcdermott** [comment] 2024-08-22 23:31
To update here -- my test case was wrong, this issue is present.

I think I know the issue though. 

In our algorithm, we identify the start and end boundaries of each window in a possible realization of a config in a patient's record, and we often do joins across the recursion calls by `subject_id` and `*_anchor_timestamp` to match different windows together over the iterations. But, this fails to consider the idea that the start window of one branch might correspond to the end window or another branch in an inappropriate manner (e.g., for a config that models to admission and discharge, in one possible extraction the end of the config--the discharge--could conflict with the start of a subsequent extraction if the patient were admitted on the same day as they were discharged).

**Comment by mmcdermott** [comment] 2024-08-24 00:52
@Oufattole I think we just pushed a fix to main for this. No new release yet, but our test case that we added for your use now passes, just as a heads up.

**Closed** 2024-08-24 00:52 UTC
Labels: Bug, priority:critical, Impacts Benchmark
